update CORS
npmStart0/server pull request #13
Opened 2024-09-28 21:12 UTC by MiriamKapach

2024-11-16 20:29 UTC, DvoraShechter1 reviewed
LGTM
Are you check it?

2024-11-16 20:29 UTC, DvoraShechter1 commented on WebApi/Program.cs
> +
Please delete unnecessary line

2024-11-27 10:36 UTC, DvoraShechter1 commented
Conflicts must be dealt with before requesting a review.

2024-12-23 17:12 UTC, RutiRozenberg commented on WebApi/Program.cs
> +
This line is necessary for the system to function properly. If removed, the application will not be able to load the settings from the .env.local file.

2025-01-13 18:31 UTC, DvoraShechter1 requested changes
The code looks great and professional.
(note the comment below).
Has the run been tested by you?

2025-01-13 18:31 UTC, DvoraShechter1 commented on WebApi/Program.cs
> +Console.WriteLine(clientUrl);
Please delete unnecessary log before merging changes.

2025-01-13 21:26 UTC, RutiRozenberg commented
The run was tested by me.

2025-01-14 16:38 UTC, DvoraShechter1 approved these changes
Perfect!
Good job!

2025-01-14 16:40 UTC, merged