Returning the error 400 instead of 500 when creating a new object with non-existent foreign keys.
npmStart0/server pull request #9
Opened 2024-09-24 12:26 UTC by estush

Resolving #7

2024-09-24 15:09 UTC, RutiRozenberg requested changes
Hi @estush 

Great job on the code! I appreciate your effort in implementing the feature. I have some improvements based on our project conventions:

1. Variable Names: Please revert any variable names that you did not create and have changed back to their original names.
2. Underscores: Remove underscores before variables according to our project conventions.
3. Default Variable Permission: Default variable permission is private, no need to add it manually.
4. Validation Function: Create a function to check if linked object keys are linked to existing objects. Use this function during object creation and updates to prevent duplicate code.Your function should be last to avoid conflicts.
5. Data Validation: Ensure data validation is performed during updates as well, not just during creation.

Regarding the file: WebApi/Controllers/CommentController.cs
- Rearrange functions to match the original project order. 
- Remove the following lines:
 <<<<<<< HEAD (line 64)
 ======= (line 171)
 >>>>>>> 9a62b7be341259c3625e9f3811aaf962b0b92384 (line 175)

Please let me know if you have any questions or need further clarification on these points.

2024-09-26 07:55 UTC, RutiRozenberg commented
Hi @estush , I noticed that the commit messages could be more descriptive and specific. It would be helpful to use meaningful commit message titles that explain the changes made in each commit. This will improve code readability and make it easier to understand the purpose of each change. Please consider updating the commit messages accordingly. Thank you!

2024-09-26 08:37 UTC, estush commented
OK

‫בתאריך יום ה׳, 26 בספט׳ 2024 ב-10:56 מאת ‪Ruti Rozenberg‬‏ <‪
***@***.***‬‏>:‬

> Hi @estush <https://github.com/estush> , I noticed that the commit
> messages could be more descriptive and specific. It would be helpful to use
> meaningful commit message titles that explain the changes made in each
> commit. This will improve code readability and make it easier to understand
> the purpose of each change. Please consider updating the commit messages
> accordingly. Thank you!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/npmStart0/server/pull/9#issuecomment-2376200683>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BGMNBRWPS3N4YDKB4RW77ATZYO4ZNAVCNFSM6AAAAABOYF5RUOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGNZWGIYDANRYGM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-09-26 09:51 UTC, MichalYiloz commented
#10  
-my Issues
Thank you!

2024-11-16 20:21 UTC, DvoraShechter1 commented
Conflicts must be dealt with before requesting a review.

2024-11-26 22:21 UTC, RutiRozenberg approved these changes, later dismissed

2024-11-27 09:41 UTC, DvoraShechter1 requested changes
Just a few small changes and this PR will be good to go.

2024-11-27 09:41 UTC, DvoraShechter1 commented on WebApi/Controllers/CommentController.cs
> +            userValidations = usValidate; // ����� �� UserValidations
Please remove unclear comment.

2024-11-27 09:41 UTC, DvoraShechter1 commented on WebApi/Controllers/CommentController.cs
> +
Please remove an empty line.

2024-11-27 10:10 UTC, DvoraShechter1 approved these changes
LGTM!

2024-11-27 10:13 UTC, merged